### ISSUE TITLE
Flutter Web Support

### ISSUE THREAD

**Issue by plusema86** [bmw-tech/atlas#50]
Is support to flutter web planned? I've discover Atlas searching on pub.dev with the "Web" filter on, but I couldn't find anything about it on this repo.

Thanks

**Comment by jorgecoca** [comment]
Atlas itself could operate on web, since it does not have any platform code... but the plugins are a different story. AFAIK all the plugins supported worked thanks to platform channels, so that's where the current limitations are, but if someone/the community creates plugins that are supported on web, Atlas will supported without any problems.

**Comment by fvisticot** [comment]
Any news or new provider allowing to use atlas with Web ? It would be awesome !!

**Comment by oguibueno** [comment]
> Any news or new provider allowing to use atlas with Web ? It would be awesome !!

Do you have anything Web specific that you want to use with Atlas?
